# Data samples that gonna be used to calculate the similarity
samples = dict(
    recommendations = [
"A faire et a refaire sans hésiter",
"Nous recommandons vivement.",
"Je recommande vivement cet hôtel",
"Nous recommandons vivement cet hôtel pour un séjour en couple.",
"La prochaine fois nous y dînerons",
"Je recommande chaudement l'endroit.",
"Nous y retourneront.",
"Je reviendrai avec plaisir",
"Je dois avouer que je n'ai pas été déçu.",
"En effet pas apprécié.",
"Je recommande Empreinte Hôtel à tout égard !",
"Je n'ai pas été déçu !",
"Nous le recommandons.",
"Nous y reviendrons volontiers.",
"Pour s'assurer que nous reviendrons à coup sûr !",
"Je recommande cet hôtel à tous ceux qui visitent",
"Sûr, nous reviendrons.",
"Nous ne recommandons pas cet établissement.",
"nous y reviendrons.",
"A refaire avec grand plaisir",
"Excellent séjour dans une très belle région, on reviendra!",
"Nous le conseillons vivement .",
"À éviter !",
"Bref je vous le recommande.",
"N'hésitez pas une seule seconde !",
"si nous revenons, nous reviendrons",
"A la prochaine fois",
"Nous reviendrons lors d'une prochaine escale",
"Très belle découverte nous reviendrons",
"Je recommande +",
"Je reviendrai sans hésiter car il y a le calme et une restauration digne des grands chefs",
"Je le recommande vivement !",
"Je conseille et je reviendrai assurément.",
"J'y retournerai certainement la prochaine fois que je suis en ville.",
"J'y retournerais avec plaisir ! !",
"Je recommande vivement !",
"Nous recommandons fortement cette auberge",
"Une étape fort agréable que nous renouvellerons volontiers.",
"Nous y retournrerons à la première occasion.",
"je le recommande fortement Jai tout aimé",
"Assez déçue!",
"Il me tarde d'y retourner.",
"Étape que je recommande vivement :-)",
"J'y retournerais volontiers",
"Sans hésitation, nous recommandons cet établissement.",
"très désagréable.",
"on y revient avec plaisir!",
"mais je ne peux que recommander cet hôtel",
"Un peu déçue.",
"Bref je recommande très vivement !",
"C'est décevant et totalement contraire à l image de marque du groupe.",
"J'y retournerais volontiers",
"Séjour à refaire sans aucun doute.",
"je le recommande",
"Nous y reviendrons.",
"J'espère un remboursement rapide!",
"Pas memorable.",
"Nous reviendrons certainement escale là encore.",
"Étape ou séjour à recommander !",
"C'est une honte !",
"Nous y retournerons certainement.",
"Je recommande pour ceux qui sont au passage dans la région.",
"Sommes contents de revenir dans ce Mercure pour une escapade.",
"Nous recommandons !",
"Je recommande sans aucune restriction.",
"C’est vraiment dommage.",
"Un peu déçu.",
"Nous reviendrons avec plaisir",
"A refaire sans problème.",
"non apprécié",
"J'adore cet hôtel il répond à tous mes besoins.",
"Cherchez mieux !",
"nous reviendrons l’été prochain .",
"Nous voulons y retourner.",
"Nous reviendrons avec grand plaisir",
"Je recommande très sincèrement ce domaine.",
"Pas génial",
"Très décevant",
"Rien a dire de plus à part que j'y retournerai à l'occasion.",
"à y revenir.",
"Nous conseillons vivement cet endroit charmant !",
"C est avec plaisir que je reviendrai.",
"J'y repasserai certainement.",
"Nous reviendrons c'est sur!",
"C'est vraiment dommage !",
"vraiment très déçu",
"Je recommande cet hôtel à toute personne qui cherche un petit Hotel sympa",
"On recommande chaudement.",
"Je n'aurais aucune hésitation à recommander cet hôtel.",
"Mais cette fois c'est la déception.",
"Je recommande vivement!",
"Je n'hésiterai pas à revenir pour mes prochains séjours.",
"Je recommande vivement",
"Pour nous, quasi un sans faute et on pense y revenir",
"Honte a ibis, honte au goupe accord.",
"Je vais y surement revenir.",
"Il faut revenir le plus vite possible.",
"Je recommande vraiment cet hôtel !",
"Je recommande fortement !",
"Nous reviendrons très certainement !",
"Je recommande largement cet hôtel !",
"Une belle parenthèse nous reviendrons!",
"agréable, dans un cadre authentique, je recommande fortement",
"Je le conseille vivement",
"très déçu",
"Nous conseillons cet établissement sans aucun problème.",
"Je recommande cet hôtel pour une étape d'une nuit.",
"dommage !",
"Bref nous recommandons.",
"Nous reviendrons avec le plus grand plaisir",
"Je recommande sans hésité ce camping.",
"un w.e de détente que nous allons renouveler!",
"Nous y retournerons avec grand plaisir",
"Génial, je recommande vivement.",
"Très belle surprise",
"on recommande +",
"C'est toujours avec plaisir que nous revenons",
"Bravo je recommande cet endroit.",
"A recommander pour une escale hors du temps.",
"Nous recommandons vivement cet hôtel",
"On reviendra ,c'est sur quand on passera dans la région",
"Très déçue",
"Nous y retournerons sans hésiter",
"pas très pratique !",
"J'y reviendrai très prochainement avec plaisir",
"A recommander sans hésiter.",
"Nous ne pouvons que recommander cet hôtel.",
"J'y retournerai sans problèmes, les proprios sont absolument charmants!",
"Donc c est un hôtel que je peut conseiller",
"C'est vraiment lamentable.",
"je recommande cet endroit!",
"Une horreur.",
"passez votre chemin.",
"Super séjour je recommande l’hôtel.",
"je recommande cette établissement",
"Je recommande vivement cet hôtel pour un séjour dans la région.",
"Je ne peut que recommandé cette hôtel",
"Nous sommes enchantés de notre séjour et y retournerons!",
"J'y retournerais.",
"Je recommande vraiment.",
"Je vous le recommande .",
"Pas super.",
"J'y retournerai.",
"Bref, je vous conseille cet hôtel.",
"Notre séjour a été, c’est avec plaisir que nous y reviendrons.",
"Je recommande cet hotel vivement.",
"L'essentiel y était et je le recommande.",
"Pas franchement génial .",
"Y reviendrons une prochaine fois.",
"Vivement conseillé !",
"Je recommande vivement cet hôtel .",
"Un hôtel que nous recommandons !",
"Je pense que je peux le recommander.",
"On y reviendra.",
"je n'hésiterais pas a y retourner.",
"Vous ne serez pas déçus par les quantités.",
"Nous reviendrons sans hésiter dans cet établissement.",
"Et nous le conseillons à tous!",
"C'est vraiment dommage.",
"il faudra surement revenir sans hésiter",
"Je reviendrai si je dois passé par là",
"Je recommande l'hôtel",
"Je reviendrais avec un grand plaisir",
"Bref tout n'est pas parfait, je ne recommande pas.",
"Au plaisir d’y revenir.",
"nous le recommandons.",
"Juste réservez !",
"À revenir !",
"En résumé : n'y allez pas.",
"hotel est vraiment excellent.nous le recommandons",
"Bref on reviendra et nous le conseillerons",
"Je recommande plus plus",
"Je trouve cela inadmissible.",
"Je reviens avec grand plaisir.",
"Nous recommandons vivement !",
"Ne pas hésitez à visitez !",
"Non cela n'est pas au niveau.",
"Je recommande cet hotel +++",
"Nous repartirons, c'est certain.",
"A renouveler avec grand plaisir .",
"Je recommande vivement cet hôtel sur la région",
"Nous reviendrons pour notre prochain séjour",
"Nous y reviendrons sans hésitation aucune.",
"on reviendra car nous sommes pas loin !",
"Nous le recommandons vivement.",
"Pas déçu.",
"Nous reviendrons sans hésitation .",
"une chose est sur,nous y retournerons dès que possible.",
"Si je dois m'arrêter à nouveau dans le coin, aucun doute que c'est ici que je viendrai.",
"Paser votre chemin!",
"Nous y retournerions sans hésiter !",
"J'y retournerai à coup sûr !",
"J'y retourne dès que l'occasion se présente!",
"ne pas hésiter vous serez séduits",
"pas déçu",
"allez !",
"Nous reviendrons pour visiter la region.",
"Honnêtement, déception totale.",
"Allez y en toute confiance .",
"Nous vous conseillons vivement de vous arrêter dans cet endroit magnifique.",
"Lamentable !",
"j’y vais souvent c’est très très bon, je vous conseille fortement",
"Merci encore à vous et je recommande cet hôtel.",
"On reviendra sans hésitations!",
"Nous recommandons +",
"A reserver sans hesiter.",
"A refaire sans aucun doute!",
"On vous le recommande.",
"Certain, j'y reviendrai à l'occasion.",
"Pas cool!",
"C'est vraiment la déception.",
"Je recommande ++",
"On y reviendra sans hésitations.",
"A part cela j'y retournerai sans problème.",
"je retourne",
"Je recommande vivement",
"Très déçu par ces personnes",
"Vraiment vraiment pas top.",
"Nous recommandons vivement cet hôtel",
"bref je ne suis pas satisfait",
"N hésitez pas à faire un petit détour pour vous arrêter là ,vous ne regretterez pas !",
"Je ne peux que recommander cette établissement!",
"je conseille +",
"je recommande et je reviendrais",
"Nous recommandons vivement cet établissement hôtelier.",
"c'est tristounet.",
"J'y retournerais sans hésiter",
"continuez ainsi .",
"A chaque visite, on se dit qu'il faudra revenir pour un séjour plus long.",
"Nous recommandons.",
"Tout était super, j'y retournerai sans soucis",
"A refaire sans aucune hésitation",
"Allez-y, vous ne serez pas déçus",
"Etablissement que je recommande chaleureusement.",
"une honte",
"Très déçus .",
"on vas y retourner",
"Très bien, a refaire.",
"au top.j'y retournerai",
"J'y reviendrai le plus souvent possible",
"Allez-y sans hésitation",
"Lors de mon prochain passage je reviendrai sans aucuns doutes.",
"Établissement que je recommande fortement.",
"Je recommande vivement.",
"À refaire!",
"à conseiller!",
"N'hésitez pas foncez !",
"je recommande l'auberge",
"j y reviendrais, super cuisine!",
"Je conseille vivement cet endroit pour passer un bon moment en toute sécurité et de convivialité.",
"Rien, j'étais plus que déçu !",
"Vous pouvez vous y arrêter vous ne serez pas deçu.",
"Je recommande pour soirées étapes 100 euros !",
"C'est un hôtel que je recommande cet hôtel.",
"A revoir vite car on est au pays du foie gras tout de même.",
"Très déçue .",
"Mais à par cela nous sommes prêt à y retourner et à le conseiller.",
"On y retournera dès qu'on repassera dans le coin.",
"Grosse erreur.",
"Vous ne serez pas déçus",
"Je recommande fortement cet établissement.",
"Nous reviendrons, c'est sûr!",
"Je recommande vivement de venir dans cet hôtel.",
"Quelle déception !",
"C'est dommage!",
"un établissement que je recommande vivement!",
"On reviendras surement .",
"Nous reviendrons et en ferons de la publicité autour de nous",
"je conseil cet hôtel",
"Pas terrible",
"Je conseille vivement cet hôtel.",
"Je reviendrai plus tranquillement pour apprécier à sa juste valeur",
"Nous y reviendrons prochainement.",
"Pour le prix j'y retournerai sans réfléchir!",
"Nous recommandons cette hôtel sans hésiter.",
"Je m'arreterai à nouveau lors de mon prochain passage.",
"Très déçu globlement.",
"Je recommande vivement cet endroit ️",
".Je vous recommande cet établissement.",
"Vraiment pas au niveau",
"A recommander sans modération !",
"Je n'hésiterais pas à y retourner et je le recommande aux plus perspicaces des voyageurs.",
"Je le conseille vivement car les prix sont doux.",
"ons reviendra c sur que du plaisir. super!",
"allez y !",
"C'est un hôtel que nous recommandons avec plaisir!",
"Si vous passez dans le coin, n'hésitez pas à faire un détour.",
"Moi je peux plus allez dans votre etablissement",
"Cela ne donne pas envie",
"J'aimerais cependant revenir ici.",
"Allez-y vous ne le regretterez pas !",
"C’était horrible.",
"Quelle belle surprise .",
"Ce n'est pas acceptable.",
"Je recommande cet hôtel",
"à recommander.",
"N'hésitez surtout pas, arrêtez-vous.",
"Nous conseillons fortement cet établissement.",
"Nous recommandons vivement",
"Recommande vraiment cet hôtel !",
"Une horreur !",
"Mais FONCEZ. Ca les vaut !",
"C’est assez désagréable !",
"Je recommande sans hésiter.",
"Nous recommandons cet hôtel très calme de surcroît.",
"Passez votre chemin.",
"J y reviendrai",
"parfait nous recommandons cet Hotel.",
"je recommande si vous rayonnez",
"Un peu déçue !",
"Déçu pour un Kyriad.",
"Nous reviendrons sûrement !",
"Je recommande fortement.",
"C'est vraiment inadmissible!",
"Très déçu mauvais acceuil",
"merci je recommande vivement cet hotel",
".à recommander vraiment",
"Catastrophique pour les jeunes qui m'accompagnaient!",
"Nous repasserons.",
"Je recommande cet établissement.",
"J'y retournerais volontiers",
"Je vous le recommande sans problème.",
"Je reviendrais et je recommande",
"Je recommande vivement cet établissement",
"Pire !",
"N'hésitez pas à vous arrêter dans cette auberge sans prétention.",
"Continuez comme ça.",
"Passer votre chemin.",
"Vite passer à autre chose et oublier ce séjour gâché.",
"Chère et pas très bon",
"Je reviendrais sans soucis.",
"Les enfants recommandent cet établissement.",
"J'ai hâte de revenir chez vous.",
"gentillesse a refaire",
"Je recommande vivement cet hôtel !",
"Allez y vous ne serez pas déçu",
"Nous y retournerons dès que nous aurons l'occasion de repartir",
"Sans aucun doute, nous y reviendrons",
"On reviendra sans hésiter!",
"Nous le conseillons a 1000% et nous reviendrons assez vite",
"nous recommandons cet hôtel !",
"Nous recommandons très très fortement.",
"Ne pas hésiter !",
"Suis déçu par rapport à mon précédent séjour .",
"Nous reviendront très bientôt avec toute la famille .",
"On adore et on y reviendra pour une 3ème fois",
"Et envie de revenir tester une suite.",
"Parlez en autour de vous.",
"C’est dommage",
"Très grosse déception à l'arrivée.",
"Nous reviendrons !",
"Un endroit où j'aimerais revenir",
"Sans aucun hésitation, j'y séjournerai de nouveau si je passe dans la région.",
"Je conseille fortement et je reviendrai.",
"On y retournera sans hésitation.",
"Je n'hésiterais pas pour y revenir.",
"hotel très apprécier, retournerai avec grand plaisir.",
"Juste très décevant",
"Nous y retournerons avec plaisir",
"tous étais bien rien a dire de plus et que je reviendrai avec un grand plaisir",
"Merci nous recommanderons cet établissement .",
"très déçue",
"Nous serions heureux d'y retourner",
"Super resto que je recommande.",
"Nous y retournerions sans hésiter.",
"Bref, on y retourneras",
"Je recommande fermement.",
"passez votre chemin si vous tenez à votre santé !",
"Je recommande chaudement !",
"Pas très correcte.",
"Nous y retournerons sans aucune hésitation.",
"Quel dommage",
"A refaire sans hésitation.",
"Nous y repasserons lors d'un passage dans ce secteur,.",
"Nous recommandons avec plaisir.",
"Mais je recommande cet hôtel.",
"C'est bien dommage.",
"je recommande vivement",
"Pour notre prochain sejour, nous y retournerons, c’est certain!",
"Nous y reviendrons avec plaisir.",
"Je recommande fortement cet hôtel.",
"surtout, ne pas s'en priver.",
"Nous recommandons chaudement.",
"à recommander vivement",
"Je recommande vivement cet hotel.",
",on y retourneras sans problème.",
"Allez y les yeux fermés, vous ne serez pas déçus !",
"Trop cool !",
"Je vous recommande vivement cette hôtel",
"Sans hésiter, nous y retournerons.",
"je recommande cet hôtel !",
"Nous n'hésiterons pas à y revenir",
"séjour décevant.",
"Nous y reviendrons !",
"Nous y retournerons.",
"Un peu déçu par leur gastronomie peu varier",
"Assez déçu",
"Mais je recommande totalement !",
"vous ne seriez pas déçu.",
"Si vous pouvez aller ailleurs, n'hésitez pas.",
"Je le recommande fortement!",
"A refaire !",
"c'est encore pire que ce que je pensait.",
"Bref, très bon moment, je recommande à 100% et y retournerai volontier.",
"nous y retournerons.lors de notre passage dans les environs",
"C'était notre première expérience, grosse déception.",
"A réserver sans inquiétude!",
"Je recommande cet hôtel à tous !",
"Nous reviendrons",
"Je recommande fortement!",
"Nous recommandons la région et l'hôtel !",
"nous n'hésiterons pas à revenir.",
"D une tristesse envahissante!",
"Mais nous reviendrons avec grand plaisir",
"Bonne continuation, nous reviendrons!",
"Une très belle découverte où on retourne pour le faire découvrir à la famille.",
"A faire, sans hésitation !",
"Il faut y aller.",
"Bravo continuez comme ça, nous reviendrons",
"Bref, vraiment pas terrible.",
"Je recommande grandement.",
"Nous connaissions déjà et nous reviendrons !",
"Bref, nous décommandons cet hotel",
"Pas tres agreable.",
"Je recommande fortement cet endroit.",
"Délicieux, je recommande.",
"Je recommande a 2000 %",
"Nous ne manquerons pas d'y revenir.",
"établissement de qualité que je recommande.",
"Je n'hésiterais pas à y retourner.",
"Je recommande l’hôtel pour un petit séjour",
"J'y retournerai avec un grand plaisir, le top",
"Nous avons vraiment hâte d'y retourner pour un plus long séjour.",
"J y retournerai avec grand plaisir.",
"Sinon on reviendra",
"Venu plusieurs fois je n'ai jamais été déçu.",
"Que du bonheur on y revient chaque fois que l'on est dans la region",
"Nous reviendront avec un grand plaisir",
"J'y repasserais avec plaisir.",
"pas très bien",
"Nous revenons toujours avec plaisir",
"grosse déception.",
"Pas content du tout.",
"Nous y retournerons sans aucune hésitation",
"Bravo c'est une adresse à recommander.",
"Nous recommandons cet établissement",
"A refaire sans hésitation !",
"C'est scandaleux !",
"C'est vraiment dommage",
"Une adresse à retenir où j'aurais beaucoup de plaisir à revenir.",
"A revenir dans cette région c'est ici que je redescendrai sans aucun problème",
"bref pas terrible",
"Un établissement que je conseille absolument",
"Allez y sans aucun doute vous ne serez pas déçu.",
"J'ai hâte d'y retourner.",
"non satisfaite",
"Je n'hésiterai pas à m'y rendre à nouveau si l'occasion m'en était donnée.",
"Nous recommandons cet établissement.",
"Bref nous avons été satisfait de notre choix et nous n'hésiterons pas à revenir si nous sommes dans le coin",
"Je suis un habitué, je recommande fortement cet établissement.",
"Je recommande vraiment !",
"Je recommande pour tous",
"Entre amis ou repas d'affaire, je n'ai pas été déçu.",
"C'est très décevant!",
"Nous recommandons vivement cet établissement.",
"J'aimerais bien y retourner.",
"Quelle chance d'avoir une telle institution à proximité",
"Très très très très déçue !",
"Je conseille vivement cet hôtel à qui veut visiter le coin.",
"vraiment dommage.",
"je recommande sans hésiter .",
"Nous reviendrons sans la moindre hésitation !",
"Je recommande sans la moindre réserve.",
"nous vous le recommandons sans hésiter",
"Nous y retournerons avec le plus grand plaisir!",
"€ pour ça , une honte !",
"Vous serez déçus",
"Vraiment déçu!",
"Nous recommandons vivement cet établissement qui a beaucoup de cachet",
"Je pense que vous ne serez pas déçu.",
"J'y retournerais sans hésiter.",
"Tout était parfait, nous reviendrons avec nos enfants.",
"Je recommande donc cet établissement sans restriction !",
"Très déçus !",
"c'est sûr , on y reviendra !",
"C'est vraiment désagréable.",
"nous reviendrons avec plaisir.",
"Déçus du début à la fin !",
"On reviendra encore avec plaisir!",
"Nous y retournerons avec grand plaisir!",
"On y retournera",
"-end pas terrible .",
"On revient toujours avec plaisir et sans crainte",
"Nous avons hâte d'y retourner, pour nous régaler à nouveau.",
"J'y reviendrais et je le conseille fortement.",
"Accueil très chaleureux, on reviendra !",
"Très bon séjour j'y retournerai",
"Je recommande a 100%",
"Je recommande cette etablissement",
"Nous y retournerons certainement",
"N'hésitez pas à faire étape dans cet établissement.",
"Je vais l'utiliser à nouveau à coup sûr.",
"Je recommande vraiment cet hôtel.",
"Mais la prochaine , sans moi !",
"Pour le travail c'est pas génial.",
"Lors d'un prochain séjour nous allons réserver sans hésitation dans cet établissement.",
"Je pense y retourner.",
"Nous le recommandons",
"Allez-y les yeux fermés, vous ne serez pas déçu.",
"Je n hésiterai pas à y revenir quand nous aurons à redescendre dans le sud.",
"A recommander sans retenue pour une étape.",
"Les enfants m'ont fait promettre de les ramener encore.",
"Recommande vivement cet établissement",
"A refaire sans hésiter",
"Si vous passez, n'hésitez pas",
"Nous n’y retournerons pas",
"Endroit à recommander.",
"Je recommande cet hôtel pour un séjour d'une nuit",
"Je recommande chaleureusement.",
"Très déçus",
"J'ai hâte de revenir",
"J'ai adoré cet hôtel.",
"A découvrir absolument si vous êtes dans le coin, ne cherchez pas ailleurs.",
"Très déçu.",
"Je recommande cet hôtel pour un week end, un court séjour.",
"Bref tout est parfait je recommande vivement .",
"Nous reviendrons avec grand plaisir!",
"Nous y reviendrions sans problème.",
"Très bien confortable je le recommande",
"Vraiment très décevant.",
"A recommander, sans hésitation!",
"Déjà hâte d'y retourner.",
"Arretez de mentir à vos clients !",
"Je recommande à faire vivement",
"faites demi-tour",
"On y retournera, tout le monde était ravi.",
"A refaire avec plaisir.",
"JE REVIENDRAI QUAND JE SERAI DE PASSAGE.",
"Nous avons hâte d'y retourner.",
"Nous reviendrons assurément !",
"Nous allons d’ailleurs vite y revenir.",
"Nous y retournerons sans hésiter je recommande!",
"jamais déçu.",
"Moi, j'y reviendrai bien volontiers.",
"Un hôtel que je conseille fortement!",
"Je n’y retournerais pas .",
"Nous conseillons cet hotel",
"Je trouve cela inadmissible ….",
"Mieux vaut aller voir alentours",
"Je pense que nous reviendrons sans aucune hésitation!",
"Nous reviendrons avec grand plaisir",
"Bref, je le recommande vivement.",
"Continuez comme ça !",
"Rien à redire et j'y reviendrai avec grand plaisir.",
"Pas super agréable.",
"Tellement nous nous sommes plus.",
"Nous reviendrons sans aucun doute à ce petit bijou.",
"Hôtel très bien situé, je le recommande vivement.",
"Parc magnifique nous y retournerons très prochainement.",
"je recommande ce sejour",
"On c'est régalé.si on repasse dans le coin on revient",
"J'y retournerai avec plaisir.",
"A conseiller à tous ceux qui cherchent un moment de qualité.",
"Nous recommandons vivement cet hôtel.",
"Première et franchement pas déçue",
"Je recommande vivement",
"je recommande fortement ce lieux pour une jolie parenthèse enchantée .",
"A recommander sans modération.",
"Au final, j'étais plutôt déçu.",
"Vaut vraiment la peine d'y aller",
"Je reviens vous voir très bientôt",
"On y retournera avec plaisir",
"regrette, déçus par la vétusté",
"Je le recommande.",
"Je recommande à 100%.",
"A recommander sans réserves.",
"Vous détailler mes déceptions.",
"Nous reviendrons avec grand plaisir",
"Je vous recommande vivement cet hôtel",
"c'est dommage",
"Nous recommandons fortement cet hôtel.",
"C'EST HONTEUX !",
"j'y suis aller plusieurs fois et j'y retournerais",
"Arrêtez vous sans hésitation.",
"Mais je recommande cet hôtel particulièrement pour les amoureux!",
"Je recommande et j'y retournerai avec grand plaisir.",
"mise a part ce petit problème tout est très bien et nous y reviendrons avec plaisir.",
"Très déçu surtout en connaissant d'autres kyriad beaucoup beaucoup mieux",
", c’était insupportable.",
"Je recommande cette hôtel a tout le monde car vraiment c'était géniale le séjour !",
"Très bien à recommander et à refaire.",
"on recommande sans hésitations !",
"Je recommande cet hôtel",
"c'est dommage !",
"On reviendra avec comme toujours un très grand plaisir.",
"Nous reviendrons prochainement!",
"Je ne regrette pas mon séjour et compte bien y revenir lorsque l’occasion se présentera à nouveau",
"je trouve ça scandaleux !",
"Je recommande vivement.",
"Quel dommage !",
"Malgré un petit bémol, je recommande fortement cet endroit!",
"Je recommande fortement cet hôtel !",
"passer votre chemin",
"Nous retournerons volontiers",
"Moi j'y retournerais les yeux fermés et avec grand plaisir !",
"Je recommande sans hésitation",
"Succulent, exquis, nous reviendrons.",
"C'était fort désagréable.",
"franchement ne vaut que la moitié décevant",
"Déçue et contrariée lors de mon séjour là-bas.",
"Je recommande cet hôtel très bien situé",
"Passez votre chemin et ne faites pas la même erreur que nous",
"Nous y Retournerons avec plaisir.",
"C'est une adresse que je conseille donc vivement",
"J'y retournerai lors de mon prochain voyage .",
"Je reviendrai ici si je retourne à Arles.",
"Faites y une escale, vous ne serez pas déçus.",
"je recommande vivement cette établissement",
"Nous recommandons ce domaine.",
"Très déçu par la prestation au vue du prix pratiqué",
"Tres bonne impression, je reviendrai.",
"Vraiment Honteux.",
"Nous ne pouvons que le recommander",
"c'est bien dommage !",
"Je suis vraiment déçu sur ce point;",
"je reviendrais sans problème.",
"Bref je recommande.",
"l'établissement est sérieux et donc à recommander.",
"Nous y retournerons sans hésiter.",
"Si je repasse par la je m'y rearreterai.",
"On y retournera lors de notre prochain périple.",
"Vraiment déçu.",
"A refaire avec plaisir",
"A recommander pour une étape !",
"Nous chercherons autre chose la prochaine fois.",
"merci au gardien , je conseil cette hôtel.",
"Je le recommande à tout le monde.",
"Tout donné envie de revenir.",
"Nous reviendrons c'est certain !",
"Si vous passez dans le coin, n’hésitez surtout",
"Nous avons passé un bon moment et sur ,nous reviendrons.",
"Nous y retournerons",
"Vraiment dommage !",
"si je repasse dans le coin je m'y arrêterait sans problème",
"Il n'y a rien à redire, sinon que l'on a envie d'y retourner et de le conseiller.",
"Je pense que nous y retournerions un jour pour avoir plus de temps.",
"je recommande +",
"Hautement recommandé.",
"on y retournera patron et personnel au top",
"A ne pas rater.",
"éviter !",
"Je reviendrai sûrement en passant dans cette région",
"Nous recommandons le lieu vivement pour une réception réussie.",
"Nous recommandons vivement cet établissement tant pour son emplacement que pour la qualité de ses prestations.",
"Je recommande cet établissement à tout le monde",
"Je conseille vivement cet établissement.",
"Bref, passez votre chemin.",
"c'est une honte, fuyez!",
"Nous reviendront avec plaisir!",
"passez votre chemin",
"Bref, je suis déçu",
"Nous sommes loin mais nous reviendrons!",
"J'y reviendrai avec plaisir !",
"Grosse déception",
"Nous y reviendrons avec plaisir !",
"Nous reviendrons à coup sûr quand nous avons l'intention un long week-end, et il y a beaucoup de choses à voir à garder un animé pour ce temps.",
"Nous recommanderions cet hôtel sans hésiter.",
"Je recommande vivement cet établissement.",
"Je recommande vivement cet hôtel et le restaurant fabuleux.",
"bien dommage !",
"dommage aussi",
"J’y retournerai et je recommande sincèrement.",
"Un peu déçu cette fois-ci.",
"Je reviendrais cet été afin de tester la piscine et la terrasse.",
"Je vous recommanderais cette Hotel pour un week-end ou plus.",
"Je vous le recommande!",
"J'y retournerai si l'occasion se présente !",
"Je recommanderais à tous",
"Nous conseillons vivement.",
"Si nous avons l’occasion nous réserverons encore",
"pensez à réserver",
"Nous y retournerons avec plaisir.",
"Nous y retournerons quand nous en aurons l'occasion.",
"Nous recommandons cet hôtel à ceux qui veulent se reposer et prendre le temps de visiter ce lieu si accueillant.",
"Je recommande cet hôtel fortement",
"Si je suis à nouveau de passage il y a de forte chance que je reprenne une chambre ici.",
"continuez ainsi et ne changez rien",
"Quelle déception!",
"Enfin sejour décevant.",
"On recommande sans problème.",
"rien à redire ,nous reviendrons facilement ,quand nous rendrons de nouveau visite à nos proches;",
"Nous repasserons sûrement.",
"Nous reviendrons certainement",
"A recommander au plus grand nombre.",
"Personnel très sympathique je reviendrai avec plaisir",
"Nous sommes prêts à y séjourner de nouveau à l'occasion !",
"Ne pas éviter ! !",
"Je reviendrai avec plaisir si mon travail nécessite de revenir dans le coin",
"Je recommande fortement cet établissement",
"Je recommande car au calme en étant à proximité de tout !",
"J'y retournerai sans utiliser un profit et peut-être pour plus longtemps.",
"A y revenir.",
"Je recommande cet hôtel sans hésiter!",
"Nous encourageons l'hôtel à poursuivre.",
"Je vous le recommande",
"En quelques minutes à pieds en plein centre du vieux Brive: je recommande vivement cet hôtel!",
"Nous conseillons cet établissement qui je pense prendra note des remarques.",
"vraiment pas terrible",
"Déçus déçus.",
"Nous y retournerons certainement à l'avenir.",
"Je recommande cet hôtel !",
"je récommande cet endroit a 100000%",
"je recommande cet établissement",
"Vieillot, défraîchi, à éviter !",
"Encore merci à toute l’équipe et à bientôt, nous reviendrons sans hésiter",
"Si un jour nous devions faire une halte dans la région, nous n'hésiterions pas à revenir.",
"Allez-y les yeux fermés, vous ne serez pas déçus !",
"ne pas venir trop chargé .",
"établissement que nous recommandons pour son accueil chaleureux ;",
"Oui, nous y retournerons en septembre.",
"C'est inadmissible!",
"Je recommande absolument.",
"Je recommande pour une occasion exceptionnelle car les prix sont à la mesure du lieu .",
"Je le recommande à tout le monde de transit ou visiter le centre commercial.",
"Je recommande fortement",
"A recommander sans hésitation.",
"On aimerait vraiment en trouver souvent des petits hôtels cosy comme cela bravo",
"Nous reviendrons avec grand plaisir.",
"C'est sûr nous reviendrons",
"A refaire sans hésiter.",
"Nous ne reviendrons jamais!",
"Nous recommandons vivement cet établissement !",
"On reviendra sûrement !",
"Vraiment, vous feriez mieux de partir !",
"Juste un mot : allez y !",
"Nous y passerons certainement un week-end lorsque nous serons à nouveau dans le coin",
"Je déconseille quand même, très déçu à l'arrivée.",
"A faire et à refaire sans hésitation !",
"J'y retournerais avec plaisir.",
"Nous y retournerons certainement à l'occasion.",
"Nous retournerons là- volontiers.",
"vivement la prochaine fois !",
"Je recommande 100 %.",
"je recommande cette établissement .",
"Je recommende vivement à mes proches !",
"Nous y reviendrons avec plaisir lors de nos déplacements familiaux.",
"Toute la famille a été conquise, donc nous reviendrons.",
"Nous n'hésiterons pas à revenir",
"Nous n'hesiterons pas à recommander votre établissement.",
"En bref et en conclusion ,faîtes le détour , cette halte sera mémorable !",
"Triste de devoir partir !",
"Très bonne expérience, nous reviendrons avec grand plaisir !",
"Je n'hésiterai pas à revenir et à conseiller mes amies de s'y rendre !",
"A l'occasion je reviendrai dans vôtre établissement.",
"Mettez y un pied et vous le regretterez",
"accueil chaleureux très bien mangé si on doit revenir dans le coin nous revenons et avec grand plaisir",
"Je le recommande",
"Continuez comme ça!",
"Continuez comme ça",
"Bref allez vite vous ressourcez au grand monarque !",
"Nous le recommandons !",
"Dommage car ceci donne une mauvaise image de la chaîne mercure !",
"Je recommande pour des courtes durées.",
"nikel.je recommande vivement",
"Grosse déconvenue !",
"Nous y retournerons volontiers pour un week-end rien qu'à nous.",
"Dans l'ensemble, je le recommande sans hésiter !",
"Nous le conseillons activement à tout le monde.",
"Penser à réserver car peu de places.",
"Nous les recommandons vivement, continuez ainsi!",
"bref je recommande ce belle hôtel restaurant en campagne.",
"Très très déçus.",
"nous continuerons à privilegier cet etablissement lors de nos sejours.",
"Un peu déçu donc.",
"Nous espérons pouvoir y retourner prochainement.",
"Je le recommande vraiment !",
"Je vous le recommande vraiment",
"Un peu déçus.",
"Très déçue de ce week",
"c'est triste de voir cela en 2013.",
"N’hésitez pas",
"Cela ne vous fera « perdre » que 5 mn mais vous ne regretterez pas",
"Très déçue !",
"Nous y retournerons sans problème pour faire une étape.",
"Bref, je vous le recommande sans hésiter!",
"J’y retournerais sans problème",
"Allez-y sans hésitation !",
"Je recommanderait cet endroit sans hésitations.",
"Une véritable honte.",
"Réservez à l'avance si vous pouvez.",
"Mystère, déception et un souvenir horrible.",
"Merci aussi pour les spécialités locales en vente à l'hôtel.",
"Nous n'hésiterons pas à revenir pour un prochain séjour.",
", font qu'on y revient.",
"On espère bien revenir le plus vite possible.",
"C'est dommage.",
"Nous reviendrons certainement l'effort de revenir ici.",
"Je vous recommande ce lieu sans aucune hésitation.",
"Nous recommandons fortement cet établissement très bon emplacement avec une très jolie vue.",
"Très déçue.",
"Nous reviendrons assurément dans c et établissement",
"Nous reviendrons très prochainement !",
"On a envie de revenir vite.",
"Passez votre chemin",
"Dommage mais ce n est pas un cas isolé",
"Pas très agréable!",
"Je conseille fortement cet hôtel",
"Laissez vous emporter dans une promenade gastronomique",
"Après une mauvaise expérience à Limoges, c’est avec grande satisfaction que nous reviendrons à Brive.",
"Je conseille cependant l'Hotel Oasis pour un weekend de repos en couple !",
"À refaire !",
"Si vous passez à Gien n'hésitez pas à vous arrêter dans cet établissement qui je vous le souhaite vous réservera le meilleur accueil.",
", on est revenu donc on a apprécié",
"- n hesitez plus allez y au plus tot et rendez vous compte par vous meme",
"Je ne peux que le recommander.",
"Nous recommandons cet hôtel.",
"J'y reviendrai sans problème.",
"Nous y retournerions si dans la région.",
"C'est certains nous y retournerons.",
"Des réunionnais qui y reviendront avec grand plaisir.",
"C'est avec plaisir que nous repasserons",
"Je suis déçu qu'il n'y ait pas de régularité de qualité et je serai plus méfiant la prochaine fois.",
"Je recommande grandement cet établissement",
"surprise en arrivant !",
"Je recommande vivement cet hôtel si vous passez dans le coin.",
"Nous reviendrons sans aucun problème et avec joie.",
"On reviendra !",
"Trop bien, des que j ai du temps j y retourne",
"C'est vraiment pas au top .",
"Nous reviendrons à coup sûr un séjour lors de notre voyage de retour en Ecosse.",
"Je le recommande sans restriction, pour des voyageurs de passage.",
"Déplorable ce séjour.",
"Nous ne manquerons pas de revenir si l'occasion se représente.",
"je le recommande vivement avec tarifs decents",
"Pensez à prendre les vôtres.",
"Je reviendrais.",
"Aucune surprise mais un peu déçu pour le prix.",
"C est dommage.",
"Nous reviendrons avec grand plaisir !",
"a recommander même de passage a proximité",
"de mieux si ce n est que l on a hâte d y retourner !",
"Nous le recommandons à tout le monde",
"Allez-y sans problème.",
"on reviendra avec plaisir.",
"Passer votre chemin",
"je recommande cet hotel",
"je recommande vivement.",
"N hésitez pas pour vs y arrêter.",
"On recommande sans hésitation.",
"Tres bon accueil je recommande vivement cet établissement.",
"Je recommanderai votre hôtel",
"Je doute que je reviendrais dans cet établissement lors d'un prochain voyage d'affaire , tarif élevé pour le service .",
"N'hésitez pas",
"Nous recommandons et reviendrons !",
"Une bonne étape et nous reviendrons sans hésitation.",
"Nous ne manquerons pas de vous recommander",
"si vous passez par là, allez y sans réfléchir.",
"Nous le recommandons vivement !",
"A Faire et refaire sans hésitation !",
"Ne pas hésiter à y aller",
"Nous reviendrons certainement.",
"Promis nous reviendrons à la fin de l'été pour bénéficier de l'été indien.",
"c'est dommage.",
"On recommande vivement.",
"Je le conseil fortement à tous.",
"Je recommande vraiment pour le prix !",
"Merci pour tout aux propriétaires, nous reviendrons si l'occasion se présente.",
"A refaire, je recommande +",
"Je redit inadmissible",
"Amené dans un futur proche à revenir à Orléans",
"Je recommande cet hotel si vous passé dans la région",
"Bravo et continuez sur la lancée.",
"Je recommande cet hôtel car c'est un bon endroit pour séjourner.",
"Nous n'hésiterons pas a revenir.",
"Allez y et profitez bien !",
"si on le peu on y retournera sans hésitation",
"On reviendra sûrement",
"A recommander sans aucune hésitation.",
"on compte bien y retrouver avec plaisir :-)",
"Je recommande donc sans problème :)",
", n’hésitez pas !",
"Continuez comme cela.",
"Je félicite les propriétaires et je reviendrais",
"Nous reviendrons très bientôt",
"On reviendra avec un grand plaisir.",
"Nous y retournerons lorsque nous repasserons par Orléans.",
"Je recommande vivement cette adresse qui permet de sortir des chaînes d'hôtellerie et de profiter d'un vrai service.",
"Je recommande cet hôtel sans hésiter, il est bien situé.",
"Je conseil cet hotel pour une nuit ( étape hotel )",
"Je reviendrais ici",
"Mais j'y retournerait avec plaisir.",
"je le recommande.",
"qui est agréable.je recommande vraiment cette hôtel.",
"Un prétexte tout trouvé pour revenir !",
"nous reviendrons c'est sûr !",
"Pour une fois, je ne trouve rien a redire et je recommande vivement !",
"Super camping très belle région, on reviendra c'est sûr",
"Grande déception",
"Bref, nous espérons sincèrement pouvoir y revenir un jour !",
"Nous pouvons conseiller cet établissement et nous reviendrons dès que possible !",
"Je conseille cet établissement.",
"On a toujours beaucoup de plaisir à revenir à cet endroit.",
"Même que j'y retournerais bien une 4 ème fois pour être sûre ;)",
"Mais déçu quand même car je restais sur l expérience des b t b de saint Malo et de la Roche sur Yon, un gros cran au dessus.",
"En conclusion, malgré les remarques sur la chambre, je recommande cet hôtel.",
"Déçue en fait par le standing français",
"Je reviendrais sans problème.",
"Un peu vieillot mais pas déçu, conforme à mes attentes.",
"ce qui est assez inadmissible et même dégoutant.",
"Je recommande cet hotel",
"Merci a eux et si vous passez par là n'hésitez pas à descendre dans cet hôtel.",
"Mais y retournerai avec plaisir",
"Nous reviendrons à coup sûr passer un autre séjour.",
"Ne pas se fier à la façade qui peux effrayer au début.",
"Allez-y sans craintes.",
"Je recommande chaudement cet hôtel hors du commun.",
"Nous y reviendrons dès que possible.",
"On espère revenir très vite!",
"vraiment pas bon",
"Nous ne regrettons pas notre halte.",
"Je recommande vivement .",
"quelle déception !",
"Je le recommande, sans problèmes.",
"Un parc reposant, nous y reviendrons avec plaisir.",
"Nous reviendrons dès que possible.",
"En quelques mots je recommande fortement cet établissement.",
"Ravie de mon séjour, je pense y revenir.",
"Je recommande vivement cet établissement pour l'accueil et le cadre.",
"J'y reviendrai avec plaisir.",
"Je reviendrai dans ce restaurant sans aucun doute.",
"Très bon séjour, nous reviendrons",
"N'y allez surtout pas !",
"On ne peut que recommander chaudement cet établissement pour son standing et sa qualité de prestations.",
"Je recommande sans aucun problème.",
"je recommande fortement ce restau c'est tellement bon",
"Je vous le recommande.",
"J'y reviendrai",
"Comportement inacceptable",
"Je recommande vivement cet hotel où l'on se sent presque comme à la maison.",
"Recommandons vivement.",
"vous ne serez pas déçu.",
"Nous reviendrons avec plaisir!",
"Avec toujours un agréable accueil, je retourne avec plaisir y séjourner pour mon travail.",
"je reviendrai un jour en voiture.",
"Je recommande vivement ce lieu",
"Très bon accueil, je reviendrai si l'occasion se représente.",
"On y retournera c est certain.",
"Nous y retournerons volontiers à l'occasion d'un prochain voyage.",
"Extrêmement déçus par la prestation de restauration :",
"Allez y !",
".Nous reviendrons sûrement lors d'un prochain voyage",
"Nous y retournerons dès que possible.",
"J'y retournerai sans aucun problème",
"Nous vous le recommandons sans plus attendre.",
"je recommande vivement ce domaine à vous couper le souffle -accueil et services exemplaire, cela fait très plaisir de découvrir ce lieu",
"Je reviendrais",
"je vous recommande cet hotel.",
"Je reviendrai volontiers",
"Lors d’une prochaine randonnée dans les Alpes mancelles, nous reviendrons, c’est sur !",
"nous reviendrons avec grand plaisir",
"Mais je pense Que la prochaine fois nous le ferons certainement",
"Rien à redire, nous n'hésiterons pas à revenir si l'occasion se présente !",
"Nous comptons y retourner.",
"Hôtel que nous recommandons.",
"Très décevant néanmoins.",
"Je recommande cet établissement qui se trouve dans une belle région.",
"Mais je recommande fortement cet arrêt si vous passer en Corrèze.",
"Je vous conseille vivement cet établissement.",
"A recommander vivement, mais pensez à réserver, car très apprécié .",
"Ce fut désagréable.",
"J'ai été agréablement surprise.",
"je recommande vivement se superbe hotel.",
"Un hôtel comme nous aimerions en trouver plus souvent.",
"j i reviendrais",
"Nous recommandons fortement votre excellent établissement :-) :-)",
"rien a redire sauf allez y sans hésitations!",
"On y retournera.",
"Nous n'hésiterons pas à y retourner si l'occasion se présente.",
"En bref je recommande aux plus grand nombres !",
"Il est en plein centre, pour un prix correct, et je le conseillerais sans hésiter.",
"C'est une honte!",
"Très désagréable!",
"A recommander vivement.",
"jamais déçu",
"J'ai adoré ce petit hôtel !",
"Nous avons déja recommandé cet hotel a nos familles.",
"Ne pas hésiter à s'y arrêter !",
"Nous y retournerons avec plaisir si l’occasion nous est donnée.",
"Je recommande vivement de séjourner ici, nous nous rappellerons ce magnifique endroit toujours !",
"Je recommande ce lieu et le personnels.",
"c’est inadmissible",
"je recommande fortement",
"À refaire",
"C'est décevant.",
"Accueil très sympathique, séjour très agréable, nous reviendrons !",
"A recommander sans détour.",
"Nous vous encourageons à continuer dans cette voie et ne manquerons pas de parler positivement de votre établissement situé dans un cadre très agréable et une magnifique région !",
"C'est avec plaisir que j'y retournerai.",
"À essayer si vous êtes dans le coin.",
"Je le recommande fortement.",
"établissement d'un nouveau genre je le recommande vivement .",
"Nous n’hésiterons pas à renouveler un futur séjour au sein de cet établissement !",
"N'ayez pas peur de réserver !",
"absolument pas à la hauteur",
"Très déçue, pas du tout à l écoute, aucune remise en question.",
"Toutefois, je chercherai mieux et ne reviendrai pas.",
"accueil.on y retourne régulierement!",
"Nous y retournerons !",
"à refaire!",
"Continuez ainsi.",
"Nous recommandons cet endroit.",
"Continuez ainsi !",
"c'est a refaire.",
"Bravo continuez.",
"Bref je le recommande a",
"Nous aurons un grand plaisir à revenir lors d'un prochain séjour",
"j'y retournerais.",
"Retournerons bien volontiers lors d’un prochain séjour",
"Je suis énormément déçu qu'on ait douté de mon honnêteté et j'ai été bafouée de mon droit de recevoir le bien que javais réservé ,peut être est-ce Parce que j'ai participé a une vente privée et n'est pas payé le prix fort.",
"C’est un hôtel que nous recommandons.",
"- De ne pas rester plus longtemps.",
"Y retournerions sans hésiter!",
"Je recommande cette appart hôtel pour tous les gens de passage à Valenciennes ou pour un plus long séjour.",
"si l occase se représente je reviendrais",
"Je recommande vivement et chaudement cet établissement.",
"Nous recommandons cet hotel sans hésiter.",
"alors n’attendez plus",
"Vivement que l'espace bien-être soit installé, pour que nous revenions au printemps prochain !",
"Nous y reviendrons avec grand plaisir.",
"Nous vous conseillons vivement se petit bijoux.",
"A recommander sans hésitation!",
"Accueil parfait, nous reviendrons rien",
"Nous attendons avec impatience notre prochain séjour !",
"Insonorisation très décevante.",
"Je le recommande vivement.",
"et au calme, nous reviendrons avec plaisir",
"Nous recommandons vivement cet endroit pour passer un très bon séjour à deux.",
"Nous ne pourrons que recommander votre értablissement.",
"Nous recommandons vivement cette adresse et souhaitons une belle réussite aux propriétaires.",
"A recommander fortement!",
"Accueil très bien, chambre propre nous reviendrons .",
"c'est inadmissible !",
"Déçu en fait.",
"Je recommande vivement l'hôtel des Esclargies pour tout séjour dans la région.",
"Ns y reviendrons",
"Bref, inacceptable!",
"C’est une belle bulle de sérénité que nous recommandons sans modération.",
"Je recommande ce lieu à tous voyageurs.",
"Nous recommencerons en espérant que les chambres seront améliorées.",
"Nous recommandons",
"N hésitez surtout pas.",
"Allez-y sans hésitations, vous ne le regretterez pas!",
"Très déçu",
"Si nous devons retourner sur Orléans ces sûr que nous y retournerons !",
"Nous y reviendrons !",
"S vous passez ou devez séjourner dans ce secteur touristique je recommande fortement cet établissement.",
"Les 5 nous nous étions d'accord pour dire que la prochaine fois nous irons ailleurs:(",
"Grosse déception dès l'arrivée, cadre loin des attentes.",
"Nous y retournerons sans aucun problème !",
"On faisait étape en famille, on ne s'y arrêtera plus.",
"intolérable !",
"Je reviendrai avec plaisir.",
", allez y.",
"J'y retournerai avec plaisir lors de mes prochains passages dans le coin et le conseillerai bien volontiers.",
"très recommandable (ce dernier point m'y a attiré).",
"J y retournerai avec plaisir",
".c'est dommage",
"Nous reviendrons sans hésiter pour notre prochaine escale en Corrèze!",
"continuer ainsi nous reviendrons avec grand plaisir D-D",
"Nous serions vraiment apprécié cet hôtel.",
"Je le recommanderai à mon entourage.",
"c'est décevant.",
"Je recommande et je reviens .",
"Nous espérons revenir.",
"Nous y retournerons à l'occasion",
"C'est notre seul regret",
"Le mans est triste pour une étape",
"Je suis vraiment plusieurs jours après furieux, car j'ai été trompé.",
"Pas l'idéal.",
"vraiment j y retournerai.",
"Je conseil vivement cet Hôtel!",
"Nous avons beaucoup apprécier et nous le recommandons",
"Personnel sympa, j'y retournerai sans problème.",
"Nous recommandons ce camping sans aucun soucis mais en nous laissant une place pour l'année prochaine.",
"Nous reviendrons c'est certain .",
"je recommande vivement cet établissement.",
"Une prochaine fois",
"Je recommande tout à fait.",
"Chambre impeccable,nous reviendrons.",
"Nous ne pouvons que recommander cet hôtel proche de beaux sites",
"nous y retournerons avec enthousiasme, même si l'addition n'est pas à la portée de toues les bourses (+- € 90,-/pers) mais cela n'est pas exagéré vu la qualité de lensemble.",
"si c'était à refaire, ce serait sans soucis!",
"A faire absolument si vous êtes dans le coin!",
"Mais soyons honnête",
"vous pouvez y aller",
"Je reviendrai dans cet établissement.",
"En général, une belle découverte que je recommande.",
"Nous recommandons cet hôtel idéalement situé.",
"Propriétaire d’une grande amabilité qui a su accommoder notre fille qui a eu une migraine, merci encore, nous espérons revenir bientôt !",
"En résumé nous recommandons sans limite.",
"Pas déçue",
"C'est très désagréable.",
"Rarement déçus.",
"J'espère vraiment y retourner dans un proche avenir!",
"On y retournera avec plaisir sur le chemin du retour!",
"Nous y reviendrons avec grand plaisir"
    ]
)
# Settings of the solution
settings = dict(
    bert_model = 'paraphrase-xlm-r-multilingual-v1', #'paraphrase-multilingual-MiniLM-L12-v2',
    sample_embedds_path = "./sample_embedds/",
    trained_xgb_model_path = "./trained_model/",
    threshold = 0.50
)