# Data samples that gonna be used to calculate the similarity
samples = dict(
    recommendations=[
        "A faire et a refaire sans hésiter",
        "Nous recommandons vivement.",
        "Je recommande vivement cet hôtel",
        "Nous recommandons vivement cet hôtel",
        "La prochaine fois nous y dînerons",
        "Je recommande chaudement l'endroit.",
        "Nous y retourneront.",
        "Je reviendrai avec plaisir",
        "Je dois avouer que je n'ai pas été déçu.",
        "En effet pas apprécié.",
        "Je recommande à tout égard !",
        "Je n'ai pas été déçu !",
        "Nous le recommandons.",
        "Nous y reviendrons volontiers.",
        "Pour s'assurer que nous reviendrons",
        "Je recommande cet hôtel",
        "Sûr, nous reviendrons.",
        "Nous ne recommandons pas cet établissement.",
        "nous y reviendrons.",
        "A refaire avec grand plaisir",
        "Excellent séjour dans une très belle région, on reviendra!",
        "Nous le conseillons vivement .",
        "À éviter !",
        "Bref je vous le recommande.",
        "N'hésitez pas une seule seconde !",
        "si nous revenons, nous reviendrons",
        "A la prochaine fois",
        "Nous reviendrons lors d'une prochaine escale",
        "Très belle découverte nous reviendrons",
        "Je recommande +",
        "Je reviendrai sans hésiter",
        "Je le recommande vivement !",
        "Je conseille et je reviendrai assurément.",
        "J'y retournerai certainement la prochaine fois",
        "J'y retournerais avec plaisir ! !",
        "Je recommande vivement !",
        "Nous recommandons fortement cette auberge",
        "Une étape fort agréable que nous renouvellerons volontiers.",
        "Nous y retournrerons à la première occasion.",
        "je le recommande fortement Jai tout aimé",
        "Assez déçue!",
        "Il me tarde d'y retourner.",
        "Étape que je recommande vivement :-)",
        "J'y retournerais volontiers",
        "Sans hésitation, nous recommandons cet établissement.",
        "très désagréable.",
        "on y revient avec plaisir!",
        "mais je ne peux que recommander cet hôtel",
        "Un peu déçue.",
        "Bref je recommande très vivement !",
        "C'est décevant et totalement contraire à l image de marque du groupe.",
        "J'y retournerais volontiers",
        "Séjour à refaire sans aucun doute.",
        "je le recommande",
        "Nous y reviendrons.",
        "J'espère un remboursement rapide!",
        "Pas memorable.",
        "Nous reviendrons certainement escale là encore.",
        "Étape ou séjour à recommander !",
        "C'est une honte !",
        "Nous y retournerons certainement.",
        "Je recommande",
        "Sommes contents de revenir",
        "Nous recommandons !",
        "Je recommande sans aucune restriction.",
        "C’est vraiment dommage.",
        "Un peu déçu.",
        "Nous reviendrons avec plaisir",
        "A refaire sans problème.",
        "non apprécié",
        "J'adore cet hôtel",
        "Cherchez mieux !",
        "nous reviendrons l’été prochain .",
        "Nous voulons y retourner.",
        "Nous reviendrons avec grand plaisir",
        "Je recommande très sincèrement ce domaine.",
        "Pas génial",
        "Très décevant",
        "Rien a dire de plus à part que j'y retournerai à l'occasion.",
        "à y revenir.",
        "Nous conseillons vivement cet endroit charmant !",
        "C est avec plaisir que je reviendrai.",
        "J'y repasserai certainement.",
        "Nous reviendrons c'est sur!",
        "C'est vraiment dommage !",
        "vraiment très déçu",
        "Je recommande cet hôtel",
        "On recommande chaudement.",
        "Je n'aurais aucune hésitation à recommander cet hôtel.",
        "Mais cette fois c'est la déception.",
        "Je recommande vivement!",
        "Je n'hésiterai pas à revenir pour mes prochains séjours.",
        "Je recommande vivement",
        "Quasi un sans faute et on pense y revenir",
        "Honte a ibis, honte au goupe accord.",
        "Je vais y surement revenir.",
        "Il faut revenir le plus vite possible.",
        "Je recommande vraiment cet hôtel !",
        "Je recommande fortement !",
        "Nous reviendrons très certainement !",
        "Je recommande largement cet hôtel !",
        "Une belle parenthèse nous reviendrons!",
        "agréable, dans un cadre authentique, je recommande fortement",
        "Je le conseille vivement",
        "très déçu",
        "Nous conseillons cet établissement sans aucun problème.",
        "Je recommande cet hôtel pour une étape d'une nuit.",
        "dommage !",
        "Bref nous recommandons.",
        "Nous reviendrons avec le plus grand plaisir",
        "Je recommande sans hésité ce camping.",
        "un w.e de détente que nous allons renouveler!",
        "Nous y retournerons avec grand plaisir",
        "Génial, je recommande vivement.",
        "Très belle surprise",
        "on recommande +",
        "C'est toujours avec plaisir que nous revenons",
        "Bravo je recommande cet endroit.",
        "A recommander pour une escale hors du temps.",
        "Nous recommandons vivement cet hôtel",
        "On reviendra ,c'est sur quand on passera dans la région",
        "Très déçue",
        "Nous y retournerons sans hésiter",
        "pas très pratique !",
        "J'y reviendrai très prochainement avec plaisir",
        "A recommander sans hésiter.",
        "Nous ne pouvons que recommander cet hôtel.",
        "J'y retournerai sans problèmes, les proprios sont absolument charmants!",
        "Donc c est un hôtel que je peut conseiller",
        "C'est vraiment lamentable.",
        "je recommande cet endroit!",
        "Une horreur.",
        "passez votre chemin.",
        "Super séjour je recommande l’hôtel.",
        "je recommande cette établissement",
        "Je recommande vivement cet hôtel",
        "Je ne peut que recommandé cette hôtel",
        "Nous sommes enchantés de notre séjour et y retournerons!",
        "J'y retournerais.",
        "Je recommande vraiment.",
        "Je vous le recommande .",
        "Pas super.",
        "dommage",
        "continuer, merci.",
        "J'y retournerai.",
        "Je vous conseille cet hôtel.",
        "C’est avec plaisir que nous y reviendrons.",
        "Je recommande cet hotel vivement.",
        "Je le recommande.",
        "Pas franchement génial .",
        "Y reviendrons une prochaine fois.",
        "Vivement conseillé !",
        "Je recommande vivement cet hôtel .",
        "Un hôtel que nous recommandons !",
        "Je pense que je peux le recommander.",
        "On y reviendra.",
        "je n'hésiterais pas a y retourner.",
        "Vous ne serez pas déçus",
        "Nous reviendrons sans hésiter dans cet établissement.",
        "Et nous le conseillons à tous!",
        "C'est vraiment dommage.",
        "il faudra surement revenir sans hésiter",
        "Je reviendrai si je dois passé par là",
        "Je recommande l'hôtel",
        "Je reviendrais avec un grand plaisir",
        "Tout n'est pas parfait, je ne recommande pas.",
        "Au plaisir d’y revenir.",
        "nous le recommandons.",
        "Juste réservez !",
        "À revenir !",
        "N'y allez pas.",
        "hotel est vraiment excellent. Nous le recommandons",
        "Bref on reviendra et nous le conseillerons",
        "Je recommande plus plus",
        "Je trouve cela inadmissible.",
        "Je reviens avec grand plaisir.",
        "Nous recommandons vivement !",
        "Ne pas hésitez à visitez !",
        "Non cela n'est pas au niveau.",
        "Je recommande cet hotel +++",
        "Nous repartirons, c'est certain.",
        "A renouveler avec grand plaisir .",
        "Je recommande vivement cet hôtel",
        "Nous reviendrons pour notre prochain séjour",
        "Nous y reviendrons sans hésitation aucune.",
        "on reviendra",
        "Nous le recommandons vivement.",
        "Pas déçu.",
        "Nous reviendrons sans hésitation .",
        "nous y retournerons dès que possible.",
        "aucun doute c'est ici que je viendrai.",
        "Paser votre chemin!",
        "Nous y retournerions sans hésiter !",
        "J'y retournerai à coup sûr !",
        "J'y retourne dès que l'occasion se présente!",
        "ne pas hésiter vous serez séduits",
        "pas déçu",
        "allez !",
        "Nous reviendrons",
        "Déception totale.",
        "Allez y en toute confiance .",
        "Nous vous conseillons vivement de vous arrêter dans cet endroit magnifique.",
        "Lamentable !",
        "j’y vais souvent c’est très très bon, je vous conseille fortement",
        "Merci encore à vous et je recommande cet hôtel.",
        "On reviendra sans hésitations!",
        "Nous recommandons +",
        "A reserver sans hesiter.",
        "A refaire sans aucun doute!",
        "On vous le recommande.",
        "J'y reviendrai à l'occasion.",
        "Pas cool!",
        "C'est vraiment la déception.",
        "Je recommande ++",
        "On y reviendra sans hésitations.",
        "A part cela j'y retournerai sans problème.",
        "je retourne",
        "Je recommande vivement",
        "Très déçu par ces personnes",
        "Vraiment vraiment pas top.",
        "Nous recommandons vivement cet hôtel",
        "bref je ne suis pas satisfait",
        "N hésitez pas à faire un petit détour pour vous arrêter là ,vous ne regretterez pas !",
        "Je ne peux que recommander cette établissement!",
        "je conseille +",
        "je recommande et je reviendrais",
        "Nous recommandons vivement cet établissement hôtelier.",
        "c'est tristounet.",
        "J'y retournerais sans hésiter",
        "continuez ainsi .",
        "il faudra revenir pour un séjour plus long.",
        "Nous recommandons.",
        "Tout était super, j'y retournerai sans soucis",
        "A refaire sans aucune hésitation",
        "Allez-y, vous ne serez pas déçus",
        "Etablissement que je recommande chaleureusement.",
        "une honte",
        "Très déçus .",
        "on vas y retourner",
        "Très bien, a refaire.",
        "au top.j'y retournerai",
        "J'y reviendrai le plus souvent possible",
        "Allez-y sans hésitation",
        "Je reviendrai sans aucuns doutes.",
        "Établissement que je recommande fortement.",
        "Je recommande vivement.",
        "À refaire!",
        "à conseiller!",
        "N'hésitez pas foncez !",
        "je recommande l'auberge",
        "j y reviendrais, super cuisine!",
        "Je conseille vivement cet endroit",
        "Rien, j'étais plus que déçu !",
        "Vous pouvez vous y arrêter vous ne serez pas deçu.",
        "Je recommande",
        "C'est un hôtel que je recommande",
        "A revoir vite",
        "Très déçue .",
        "nous sommes prêt à y retourner et à le conseiller.",
        "On y retournera",
        "Grosse erreur.",
        "Vous ne serez pas déçus",
        "Je recommande fortement cet établissement.",
        "Nous reviendrons",
        "Je recommande vivement",
        "Quelle déception !",
        "C'est dommage!",
        "un établissement que je recommande vivement!",
        "On reviendras surement .",
        "Nous reviendrons et en ferons de la publicité autour de nous",
        "je conseil cet hôtel",
        "Pas terrible",
        "Je conseille vivement cet hôtel.",
        "Je reviendrai",
        "Nous y reviendrons prochainement.",
        "J'y retournerai sans réfléchir!",
        "Nous recommandons cette hôtel sans hésiter.",
        "Je m'arreterai à nouveau",
        "Très déçu globlement.",
        "Je recommande vivement cet endroit ️",
        "Je vous recommande cet établissement.",
        "Vraiment pas au niveau",
        "A recommander sans modération !",
        "Je n'hésiterais pas à y retourner et je le recommande aux plus perspicaces des voyageurs.",
        "Je le conseille vivement",
        "on reviendra c'est sur que du plaisir. super!",
        "allez y !",
        "Nous recommandons avec plaisir!",
        "N'hésitez pas à faire un détour.",
        "Moi je peux plus allez dans votre etablissement",
        "Cela ne donne pas envie",
        "J'aimerais revenir ici.",
        "C’est vraiment dommage",
        "Allez-y vous ne le regretterez pas !",
        "C’était horrible.",
        "Quelle belle surprise .",
        "Ce n'est pas acceptable.",
        "Je recommande cet hôtel",
        "à recommander.",
        "N'hésitez surtout pas, arrêtez-vous.",
        "Nous conseillons fortement",
        "Nous recommandons vivement",
        "Recommande vraiment",
        "Une horreur !",
        "Mais FONCEZ. Ca les vaut !",
        "C’est assez désagréable !",
        "Je recommande sans hésiter.",
        "Nous recommandons cet hôtel",
        "Passez votre chemin.",
        "J y reviendrai",
        "parfait nous recommandons cet Hotel.",
        "je recommande",
        "Un peu déçue !",
        "Déçu",
        "Nous reviendrons sûrement !",
        "Je recommande fortement.",
        "C'est vraiment inadmissible!",
        "Très déçu",
        "merci je recommande vivement cet hotel",
        ".à recommander vraiment",
        "Catastrophique",
        "Nous repasserons.",
        "Je recommande cet établissement.",
        "J'y retournerais volontiers",
        "Je vous le recommande sans problème.",
        "Je reviendrais et je recommande",
        "Je recommande vivement cet établissement",
        "Pire !",
        "N'hésitez pas à vous arrêter",
        "Continuez comme ça.",
        "Passer votre chemin.",
        "Vite passer à autre chose et oublier ce séjour gâché.",
        "Je reviendrais sans soucis.",
        "recommandent cet établissement.",
        "J'ai hâte de revenir chez vous.",
        "gentillesse a refaire",
        "Je recommande vivement",
        "Allez y vous ne serez pas déçu",
        "Nous y retournerons",
        "Sans aucun doute, nous y reviendrons",
        "On reviendra sans hésiter!",
        "Nous le conseillons a 1000% et nous reviendrons assez vite",
        "nous recommandons cet hôtel !",
        "Nous recommandons très très fortement.",
        "Ne pas hésiter !",
        "Suis déçu",
        "Nous reviendront très bientôt",
        "On adore et on y reviendra",
        "Et envie de revenir tester une suite.",
        "Parlez en autour de vous.",
        "C’est dommage",
        "Très grosse déception",
        "Nous reviendrons !",
        "Un endroit où j'aimerais revenir",
        "j'y séjournerai de nouveau",
        "Je conseille fortement et je reviendrai.",
        "On y retournera sans hésitation.",
        "Je n'hésiterais pas pour y revenir.",
        "hotel très apprécier, retournerai avec grand plaisir.",
        "Très décevant",
        "Nous y retournerons avec plaisir",
        "tous étais bien, je reviendrai avec un grand plaisir",
        "excellentes et délicieuses, nous conseillons vivement.",
        "Merci nous recommanderons cet établissement .",
        "très déçue",
        "Nous serions heureux d'y retourner",
        "Super je recommande.",
        "Nous y retournerions sans hésiter.",
        "Bref, on y retourneras",
        "Je recommande fermement.",
        "passez votre chemin si vous tenez à votre santé !",
        "Je recommande chaudement !",
        "Pas très correcte.",
        "Nous y retournerons sans aucune hésitation.",
        "Quel dommage",
        "A refaire sans hésitation.",
        "Nous y repasserons",
        "Nous recommandons avec plaisir.",
        "je recommande",
        "C'est bien dommage.",
        "je recommande vivement",
        "nous y retournerons",
        "Nous y reviendrons avec plaisir.",
        "Je recommande fortement",
        "surtout, ne pas s'en priver.",
        "Nous recommandons chaudement.",
        "à recommander vivement",
        "Je recommande vivement ",
        ",on y retourneras sans problème.",
        "Allez y les yeux fermés, vous ne serez pas déçus !",
        "Trop cool !",
        "Je vous recommande vivement cette hôtel",
        "Sans hésiter, nous y retournerons.",
        "je recommande cet hôtel !",
        "Nous n'hésiterons pas à y revenir",
        "séjour décevant.",
        "Nous y reviendrons !",
        "Nous y retournerons.",
        "Un peu déçu",
        "Assez déçu",
        "Mais je recommande totalement !",
        "vous ne seriez pas déçu.",
        "aller ailleurs !",
        "Je le recommande fortement!",
        "A refaire !",
        "c'est encore pire que ce que je pensait.",
        "Bref, très bon moment, je recommande à 100% et y retournerai volontier.",
        "nous y retournerons",
        "Grosse déception.",
        "A réserver sans inquiétude!",
        "Je recommande cet hôtel à tous !",
        "Nous reviendrons",
        "Je recommande fortement!",
        "Nous recommandons",
        "nous n'hésiterons pas à revenir.",
        "D une tristesse envahissante!",
        "Mais nous reviendrons avec grand plaisir",
        "nous reviendrons!",
        "Une très belle découverte où on retourne",
        "A faire, sans hésitation !",
        "Il faut y aller.",
        "Bravo continuez comme ça, nous reviendrons",
        "Vraiment pas terrible.",
        "Je recommande grandement.",
        "Nous reviendrons !",
        "Nous décommandons cet hotel",
        "Pas tres agreable.",
        "Je recommande fortement cet endroit.",
        "Délicieux, je recommande.",
        "Je recommande a 2000 %",
        "Nous ne manquerons pas d'y revenir.",
        "établissement de qualité que je recommande.",
        "Je n'hésiterais pas à y retourner.",
        "Je recommande l’hôtel",
        "J'y retournerai avec un grand plaisir, le top",
        "Nous avons vraiment hâte d'y retourner",
        "J y retournerai avec grand plaisir.",
        "Sinon on reviendra",
        "je n'ai jamais été déçu.",
        "Que du bonheur on y revient chaque fois",
        "Nous reviendront avec un grand plaisir",
        "J'y repasserais avec plaisir.",
        "pas très bien",
        "Nous revenons toujours avec plaisir",
        "grosse déception.",
        "Pas content du tout.",
        "Nous y retournerons sans aucune hésitation",
        "Bravo c'est une adresse à recommander.",
        "Nous recommandons cet établissement",
        "A refaire sans hésitation !",
        "C'est scandaleux !",
        "C'est vraiment dommage",
        "Une adresse à retenir où j'aurais beaucoup de plaisir à revenir.",
        "c'est ici que je redescendrai",
        "bref pas terrible",
        "Un établissement que je conseille absolument",
        "Allez y sans aucun doute vous ne serez pas déçu.",
        "J'ai hâte d'y retourner.",
        "non satisfaite",
        "Je n'hésiterai pas à m'y rendre à nouveau",
        "Nous recommandons cet établissement.",
        "nous n'hésiterons pas à revenir",
        "je recommande fortement cet établissement.",
        "Je recommande vraiment !",
        "Je recommande pour tous",
        "je n'ai pas été déçu.",
        "C'est très décevant!",
        "Nous recommandons vivement cet établissement.",
        "J'aimerais bien y retourner.",
        "Quelle chance d'avoir une telle institution à proximité",
        "Très très très très déçue !",
        "Je conseille vivement cet hôtel",
        "vraiment dommage.",
        "je recommande sans hésiter .",
        "Nous reviendrons sans la moindre hésitation !",
        "Je recommande sans la moindre réserve.",
        "nous vous le recommandons sans hésiter",
        "Nous y retournerons avec le plus grand plaisir!",
        "une honte !",
        "Vous serez déçus",
        "Vraiment déçu!",
        "Nous recommandons vivement cet établissement qui a beaucoup de cachet",
        "Je pense que vous ne serez pas déçu.",
        "J'y retournerais sans hésiter.",
        "Tout était parfait, nous reviendrons",
        "Je recommande donc cet établissement sans restriction !",
        "Très déçus !",
        "c'est sûr , on y reviendra !",
        "C'est vraiment désagréable.",
        "nous reviendrons avec plaisir.",
        "Déçus du début à la fin !",
        "On reviendra encore avec plaisir!",
        "Nous y retournerons avec grand plaisir!",
        "On y retournera",
        "-end pas terrible .",
        "On revient toujours avec plaisir et sans crainte",
        "Nous avons hâte d'y retourner, pour nous régaler à nouveau.",
        "J'y reviendrais et je le conseille fortement.",
        "Accueil très chaleureux, on reviendra !",
        "Très bon séjour j'y retournerai",
        "Je recommande a 100%",
        "Je recommande cette etablissement",
        "Nous y retournerons certainement",
        "N'hésitez pas à faire étape dans cet établissement.",
        "Je vais l'utiliser à nouveau à coup sûr.",
        "Je recommande vraiment cet hôtel.",
        "Mais la prochaine , sans moi !",
        "Pour le travail c'est pas génial.",
        "réserver sans hésitation dans cet établissement.",
        "Je pense y retourner.",
        "Nous le recommandons",
        "Allez-y les yeux fermés, vous ne serez pas déçu.",
        "Je n hésiterai pas à y revenir",
        "A recommander sans retenue",
        "les ramener encore.",
        "Recommande vivement cet établissement",
        "A refaire sans hésiter",
        "n'hésitez pas",
        "Nous n’y retournerons pas",
        "Endroit à recommander.",
        "Je recommande cet hôtel",
        "Je recommande chaleureusement.",
        "Très déçus",
        "J'ai hâte de revenir",
        "J'ai adoré cet hôtel.",
        "A découvrir absolument, ne cherchez pas ailleurs.",
        "Très déçu.",
        "Je recommande cet hôtel",
        "tout est parfait je recommande vivement .",
        "Nous reviendrons avec grand plaisir!",
        "Nous y reviendrions sans problème.",
        "Très bien, je le recommande",
        "Vraiment très décevant.",
        "A recommander, sans hésitation!",
        "Déjà hâte d'y retourner.",
        "Arretez de mentir à vos clients !",
        "Je recommande à faire vivement",
        "faites demi-tour",
        "On y retournera, tout le monde était ravi.",
        "A refaire avec plaisir.",
        "JE REVIENDRAI",
        "Nous avons hâte d'y retourner.",
        "Nous reviendrons assurément !",
        "Nous allons d’ailleurs vite y revenir.",
        "Nous y retournerons sans hésiter je recommande!",
        "jamais déçu.",
        "j'y reviendrai bien volontiers.",
        "je conseille fortement!",
        "Je n’y retournerais pas .",
        "Nous conseillons cet hotel",
        "Je trouve cela inadmissible ….",
        "Mieux vaut aller voir alentours",
        "Je pense que nous reviendrons sans aucune hésitation!",
        "Nous reviendrons avec grand plaisir",
        "je le recommande vivement.",
        "Continuez comme ça !",
        "Rien à redire et j'y reviendrai avec grand plaisir.",
        "Pas super agréable.",
        "Tellement nous nous sommes plus.",
        "Nous reviendrons sans aucun doute à ce petit bijou.",
        "Hôtel très bien situé, je le recommande vivement.",
        "nous y retournerons très prochainement.",
        "je recommande",
        "On s'est régalé.",
        "J'y retournerai avec plaisir.",
        "A conseiller à tous",
        "Nous recommandons vivement cet hôtel.",
        " franchement pas déçue",
        "Je recommande vivement",
        "je recommande fortement ce lieux",
        "A recommander sans modération.",
        "plutôt déçu.",
        "Vaut vraiment la peine d'y aller",
        "Je reviens vous voir très bientôt",
        "On y retournera avec plaisir",
        "regrette, déçus par la vétusté",
        "Je le recommande.",
        "Je recommande à 100%.",
        "A recommander sans réserves.",
        "mes déceptions.",
        "Nous reviendrons avec grand plaisir",
        "Je vous recommande vivement cet hôtel",
        "c'est dommage",
        "Nous recommandons fortement",
        "C'EST HONTEUX !",
        "j'y retournerais",
        "Arrêtez vous sans hésitation.",
        "Mais je recommande cet hôtel particulièrement",
        "Je recommande et j'y retournerai avec grand plaisir.",
        "tout est très bien, nous y reviendrons avec plaisir.",
        "Très déçu",
        "c’était insupportable.",
        "Je recommande cette hôtel, vraiment c'était géniale",
        "Très bien à recommander et à refaire.",
        "on recommande sans hésitations !",
        "Je recommande",
        "c'est dommage !",
        "On reviendra avec comme toujours un très grand plaisir.",
        "Nous reviendrons prochainement!",
        "Je ne regrette pas mon séjour et compte bien y revenir",
        "je trouve ça scandaleux !",
        "Je recommande vivement.",
        "Quel dommage !",
        "je recommande fortement cet endroit!",
        "Je recommande fortement cet hôtel !",
        "passer votre chemin",
        "Nous retournerons volontiers",
        "j'y retournerais les yeux fermés et avec grand plaisir !",
        "Je recommande sans hésitation",
        "Succulent, exquis, nous reviendrons.",
        "C'était fort désagréable.",
        "franchement ne vaut que la moitié décevant",
        "Déçue et contrariée",
        "Je recommande cet hôtel très bien situé",
        "Passez votre chemin et ne faites pas la même erreur que nous",
        "Nous y Retournerons avec plaisir.",
        "je conseille donc vivement",
        "J'y retournerai",
        "Je reviendrai ici",
        "Faites y une escale, vous ne serez pas déçus.",
        "je recommande vivement cette établissement",
        "Nous recommandons ce domaine.",
        "Très déçu",
        "Tres bonne impression, je reviendrai.",
        "Vraiment Honteux.",
        "À renouveler !",
        "Nous ne pouvons que le recommander",
        "c'est bien dommage !",
        "Je suis vraiment déçu",
        "je reviendrais sans problème.",
        "Bref je recommande.",
        "l'établissement est sérieux et donc à recommander.",
        "Nous y retournerons sans hésiter.",
        "je m'y rearreterai.",
        "On y retournera",
        "Vraiment déçu.",
        "A refaire avec plaisir",
        "A recommander",
        "Nous chercherons autre chose la prochaine fois.",
        "je conseil cette hôtel.",
        "Je le recommande à tout le monde.",
        "Tout donné envie de revenir.",
        "Nous reviendrons c'est certain !",
        "n’hésitez surtout pas",
        "Nous avons passé un bon moment et sur ,nous reviendrons.",
        "Nous y retournerons",
        "Vraiment dommage !",
        "je m'y arrêterait sans problème",
        "Il n'y a rien à redire, sinon que l'on a envie d'y retourner et de le conseiller.",
        "Je pense que nous y retournerions un jour pour avoir plus de temps.",
        "je recommande +",
        "Hautement recommandé.",
        "on y retournera",
        "A ne pas rater.",
        "éviter !",
        "Je reviendrai sûrement",
        "Nous recommandons le lieu vivement",
        "Nous recommandons vivement cet établissement",
        "Je recommande cet établissement à tout le monde",
        "Je conseille vivement cet établissement.",
        "Bref, passez votre chemin.",
        "c'est une honte, fuyez!",
        "Nous reviendront avec plaisir!",
        "passez votre chemin",
        "Bref, je suis déçu",
        "Nous sommes loin mais nous reviendrons!",
        "J'y reviendrai avec plaisir !",
        "Grosse déception",
        "Nous y reviendrons avec plaisir !",
        "Nous reviendrons à coup sûr ",
        "Nous recommanderions cet hôtel sans hésiter.",
        "Je recommande vivement cet établissement.",
        "Je recommande vivement cet hôtel et le restaurant fabuleux.",
        "bien dommage !",
        "dommage aussi",
        "J’y retournerai et je recommande sincèrement.",
        "Un peu déçu cette fois-ci.",
        "Je reviendrais cet été afin de tester la piscine et la terrasse.",
        "Je vous recommanderais cette Hotel pour un week-end ou plus.",
        "Je vous le recommande!",
        "J'y retournerai si l'occasion se présente !",
        "Je recommanderais à tous",
        "Nous conseillons vivement.",
        "Si nous avons l’occasion nous réserverons encore",
        "pensez à réserver",
        "Nous y retournerons avec plaisir.",
        "Nous y retournerons quand nous en aurons l'occasion.",
        "Nous recommandons cet hôtel ",
        "Je recommande cet hôtel fortement",
        "continuez ainsi et ne changez rien",
        "Quelle déception!",
        "Enfin sejour décevant.",
        "On recommande sans problème.",
        "rien à redire ,nous reviendrons facilement,",
        "Nous repasserons sûrement.",
        "Nous reviendrons certainement",
        "A recommander au plus grand nombre.",
        "Personnel très sympathique je reviendrai avec plaisir",
        "Nous sommes prêts à y séjourner de nouveau à l'occasion !",
        "Ne pas éviter ! !",
        "Je reviendrai avec plaisir ",
        "Je recommande fortement cet établissement",
        "Je recommande car au calme en étant à proximité de tout !",
        "J'y retournerai ",
        "A y revenir.",
        "Je recommande cet hôtel sans hésiter!",
        "Nous encourageons l'hôtel à poursuivre.",
        "Je vous le recommande",
        "je recommande vivement cet hôtel!",
        "Nous conseillons cet établissement",
        "vraiment pas terrible",
        "Déçus déçus.",
        "Nous y retournerons certainement à l'avenir.",
        "Je recommande cet hôtel !",
        "je récommande cet endroit a 100000%",
        "je recommande cet établissement",
        "Vieillot, défraîchi, à éviter !",
        "à bientôt, nous reviendrons sans hésiter",
        "Si un jour nous devions faire une halte dans la région, nous n'hésiterions pas à revenir.",
        "Allez-y les yeux fermés, vous ne serez pas déçus !",
        "ne pas venir trop chargé .",
        "établissement que nous recommandons;",
        "Oui, nous y retournerons.",
        "C'est inadmissible!",
        "Je recommande absolument.",
        "Je recommande pour une occasion exceptionnelle.",
        "Je le recommande à tout le monde ",
        "Je recommande fortement",
        "très déçu ",
        "A recommander sans hésitation.",
        "On aimerait vraiment en trouver souvent des petits hôtels cosy, bravo",
        "Nous reviendrons avec grand plaisir.",
        "C'est sûr nous reviendrons",
        "A refaire sans hésiter.",
        "Nous ne reviendrons jamais!",
        "Nous recommandons vivement cet établissement !",
        "On reviendra sûrement !",
        "Vraiment, vous feriez mieux de partir !",
        "Juste un mot : allez y !",
        "Nous y passerons certainement un week-end ",
        "Je déconseille quand même, très déçu à l'arrivée.",
        "A faire et à refaire sans hésitation !",
        "J'y retournerais avec plaisir.",
        "Nous y retournerons certainement à l'occasion.",
        "Nous retournerons là- volontiers.",
        "vivement la prochaine fois !",
        "Je recommande 100 %.",
        "je recommande cette établissement .",
        "Je recommende vivement à mes proches !",
        "Nous y reviendrons avec plaisir ",
        "donc nous reviendrons.",
        "Nous n'hésiterons pas à revenir",
        "Nous n'hesiterons pas à recommander votre établissement.",
        "Faîtes le détour , cette halte sera mémorable !",
        "Triste de devoir partir !",
        "Très bonne expérience, nous reviendrons avec grand plaisir !",
        "Je n'hésiterai pas à revenir et à conseiller mes amies de s'y rendre !",
        "Je reviendrai dans vôtre établissement.",
        "Mettez y un pied et vous le regretterez",
        "nous revenons et avec grand plaisir",
        "Je le recommande",
        "Continuez comme ça!",
        "Continuez comme ça",
        "allez vite vous ressourcez !",
        "Nous le recommandons !",
        "Dommage car ceci donne une mauvaise image de la chaîne",
        "Je recommande",
        "nikel.je recommande vivement",
        "Grosse déconvenue !",
        "Nous y retournerons volontiers",
        " je le recommande sans hésiter !",
        "Nous le conseillons activement",
        "Nous les recommandons vivement, continuez ainsi!",
        "je recommande",
        "Très très déçus.",
        "nous continuerons à privilegier cet etablissement",
        "Un peu déçu donc.",
        "Nous espérons pouvoir y retourner prochainement.",
        "Je le recommande vraiment !",
        "Je vous le recommande vraiment",
        "Un peu déçus.",
        "Très déçue de ce week",
        "c'est triste de voir cela",
        "N’hésitez pas",
        "vous ne regretterez pas",
        "Très déçue !",
        "Nous y retournerons sans problème",
        "je vous le recommande sans hésiter!",
        "J’y retournerais sans problème",
        "Allez-y sans hésitation !",
        "Je recommanderait cet endroit sans hésitations.",
        "Une véritable honte.",
        "déception et un souvenir horrible.",
        "Nous n'hésiterons pas à revenir pour un prochain séjour.",
        ", font qu'on y revient.",
        "On espère bien revenir le plus vite possible.",
        "C'est dommage.",
        "Nous reviendrons certainement ",
        "Je vous recommande ce lieu sans aucune hésitation.",
        "Nous recommandons fortement cet établissement ",
        "Très déçue.",
        "Nous reviendrons assurément dans cette établissement",
        "Nous reviendrons très prochainement !",
        "On a envie de revenir vite.",
        "Passez votre chemin",
        "Dommage",
        "Pas très agréable!",
        "Je conseille fortement cet hôtel",
        "c’est avec grande satisfaction que nous reviendrons",
        "Je conseille",
        "À refaire !",
        "n'hésitez pas à vous arrêter dans cet établissement",
        ", on est revenu donc on a apprécié",
        "- n hesitez plus allez y au plus tot ",
        "Je ne peux que le recommander.",
        "Nous recommandons cet hôtel.",
        "J'y reviendrai sans problème.",
        "Nous y retournerions si dans la région.",
        "C'est certains nous y retournerons.",
        "y reviendront avec grand plaisir.",
        "C'est avec plaisir que nous repasserons",
        "Je suis déçu et je serai plus méfiant la prochaine fois.",
        "Je recommande grandement cet établissement",
        "surprise en arrivant !",
        "Je recommande vivement cet hôtel si vous passez dans le coin.",
        "Nous reviendrons sans aucun problème et avec joie.",
        "On reviendra !",
        "Trop bien, des que j ai du temps j y retourne",
        "C'est vraiment pas au top .",
        "Nous reviendrons à coup sûr ",
        "Je le recommande sans restriction, pour des voyageurs de passage.",
        "Déplorable ce séjour.",
        "Nous ne manquerons pas de revenir si l'occasion se représente.",
        "je le recommande vivement avec tarifs decents",
        "Pensez à prendre les vôtres.",
        "Je reviendrais.",
        "Aucune surprise mais un peu déçu pour le prix.",
        "C est dommage.",
        "Nous reviendrons avec grand plaisir !",
        "a recommander même de passage a proximité",
        "de mieux si ce n est que l on a hâte d y retourner !",
        "Nous le recommandons à tout le monde",
        "Allez-y sans problème.",
        "on reviendra avec plaisir.",
        "Passer votre chemin",
        "je recommande cet hotel",
        "je recommande vivement.",
        "N hésitez pas pour vs y arrêter.",
        "On recommande sans hésitation.",
        "je recommande vivement cet établissement.",
        "Je recommanderai votre hôtel",
        "Je doute que je reviendrais dans cet établissement ",
        "N'hésitez pas",
        "Nous recommandons et reviendrons !",
        "Une bonne étape et nous reviendrons sans hésitation.",
        "Nous ne manquerons pas de vous recommander",
        "si vous passez par là, allez y sans réfléchir.",
        "Nous le recommandons vivement !",
        "A Faire et refaire sans hésitation !",
        "Ne pas hésiter à y aller",
        "Nous reviendrons certainement.",
        "Promis nous reviendrons à la fin de l'été ",
        "c'est dommage.",
        "On recommande vivement.",
        "Je le conseil fortement à tous.",
        "Je recommande vraiment pour le prix !",
        "Merci nous reviendrons si l'occasion se présente.",
        "A refaire, je recommande +",
        "Je redit inadmissible",
        "Amené dans un futur proche à revenir à Orléans",
        "Je recommande cet hotel si vous passé dans la région",
        "Bravo et continuez sur la lancée.",
        "Je recommande cet hôtel ",
        "Nous n'hésiterons pas a revenir.",
        "Allez y et profitez bien !",
        "si on le peu on y retournera sans hésitation",
        "On reviendra sûrement",
        "A recommander sans aucune hésitation.",
        "on compte bien y retrouver avec plaisir :-)",
        "Je recommande donc sans problème :)",
        ", n’hésitez pas !",
        "Continuez comme cela.",
        "je reviendrais",
        "Nous reviendrons très bientôt",
        "On reviendra avec un grand plaisir.",
        "Nous y retournerons lorsque nous repasserons par Orléans.",
        "Je recommande vivement cette adresse",
        "Je recommande cet hôtel sans hésiter, il est bien situé.",
        "Je conseil cet hotel pour une nuit ( étape hotel )",
        "Je reviendrais ici",
        "Mais j'y retournerait avec plaisir.",
        "je le recommande.",
        "je recommande vraiment cette hôtel.",
        "Un prétexte tout trouvé pour revenir !",
        "nous reviendrons c'est sûr !",
        "Pour une fois, je ne trouve rien a redire et je recommande vivement !",
        "Super camping très belle région, on reviendra c'est sûr",
        "Grande déception",
        "Bref, nous espérons sincèrement pouvoir y revenir un jour !",
        "Nous pouvons conseiller cet établissement et nous reviendrons dès que possible !",
        "Je conseille cet établissement.",
        "On a toujours beaucoup de plaisir à revenir à cet endroit.",
        "Mais déçu quand même ",
        "En conclusion, je recommande cet hôtel.",
        "Déçue en fait par le standing français",
        "Je reviendrais sans problème.",
        "Un peu vieillot mais pas déçu, conforme à mes attentes.",
        "ce qui est assez inadmissible et même dégoutant.",
        "Je recommande cet hotel",
        "n'hésitez pas à descendre dans cet hôtel.",
        "Mais y retournerai avec plaisir",
        "Nous reviendrons à coup sûr passer un autre séjour.",
        "Ne pas se fier à la façade qui peux effrayer au début.",
        "Allez-y sans craintes.",
        "Je recommande chaudement cet hôtel",
        "Nous y reviendrons dès que possible.",
        "On espère revenir très vite!",
        "vraiment pas bon",
        "Nous ne regrettons pas notre halte.",
        "Je recommande vivement .",
        "quelle déception !",
        "Je le recommande, sans problèmes.",
        "nous y reviendrons avec plaisir.",
        "Nous reviendrons dès que possible.",
        "En quelques mots je recommande fortement cet établissement.",
        "Ravie de mon séjour, je pense y revenir.",
        "Je recommande vivement cet établissement.",
        "J'y reviendrai avec plaisir.",
        "Je reviendrai dans ce restaurant sans aucun doute.",
        "Très bon séjour, nous reviendrons",
        "N'y allez surtout pas !",
        "On ne peut que recommander chaudement cet établissement ",
        "Je recommande sans aucun problème.",
        "je recommande fortement ce restau ",
        "Je vous le recommande.",
        "J'y reviendrai",
        "Comportement inacceptable",
        "Je recommande vivement cet hotel où l'on se sent presque comme à la maison.",
        "Recommandons vivement.",
        "vous ne serez pas déçu.",
        "Nous reviendrons avec plaisir!",
        "Avec toujours un agréable accueil, je retourne avec plaisir y séjourner pour mon travail.",
        "je reviendrai un jour en voiture.",
        "Je recommande vivement ce lieu",
        "je reviendrai si l'occasion se représente.",
        "On y retournera c est certain.",
        "Nous y retournerons volontiers à l'occasion d'un prochain voyage.",
        "Extrêmement déçus par la prestation de restauration :",
        "Allez y !",
        ".Nous reviendrons sûrement lors d'un prochain voyage",
        "Nous y retournerons dès que possible.",
        "J'y retournerai sans aucun problème",
        "Nous vous le recommandons sans plus attendre.",
        "je recommande vivement ce domaine ",
        "Je reviendrais",
        "je vous recommande cet hotel.",
        "Je reviendrai volontiers",
        "nous reviendrons, c’est sur !",
        "nous reviendrons avec grand plaisir",
        "Rien à redire, nous n'hésiterons pas à revenir si l'occasion se présente !",
        "Nous comptons y retourner.",
        "Hôtel que nous recommandons.",
        "Très décevant néanmoins.",
        "Je recommande cet établissement ",
        "Mais je recommande fortement cet arrêt ",
        "Je vous conseille vivement cet établissement.",
        "A recommander vivement,",
        "J'ai été agréablement surprise.",
        "je recommande vivement se superbe hotel.",
        "Un hôtel comme nous aimerions en trouver plus souvent.",
        "j i reviendrais",
        "Nous recommandons fortement votre excellent établissement :-) :-)",
        "rien a redire sauf allez y sans hésitations!",
        "On y retournera.",
        "Bref, n'hésitez pas à venir, ",
        "vraiment satisfaits de notre étape nous reviendrons avec plaisir l'année prochaine !",
        "Nous n'hésiterons pas à y retourner si l'occasion se présente.",
        "En bref je recommande aux plus grand nombres !",
        ",et je le conseillerais sans hésiter.",
        "C'est une honte!",
        "Très désagréable!",
        "A recommander vivement.",
        "jamais déçu",
        "J'ai adoré ce petit hôtel !",
        "Nous avons déja recommandé cet hotel a nos familles.",
        "Ne pas hésiter à s'y arrêter !",
        "Nous y retournerons avec plaisir si l’occasion nous est donnée.",
        "Je recommande vivement de séjourner ici, nous nous rappellerons ce magnifique endroit toujours !",
        "Je recommande ce lieu et le personnels.",
        "c’est inadmissible",
        "je recommande fortement",
        "C'est décevant.",
        "nous reviendrons !",
        "A recommander sans détour.",
        "Nous vous encourageons à continuer dans cette voie et ne manquerons pas de parler positivement de votre établissement ",
        "C'est avec plaisir que j'y retournerai.",
        "À essayer si vous êtes dans le coin.",
        "Je le recommande fortement.",
        "établissement d'un nouveau genre je le recommande vivement .",
        "Nous n’hésiterons pas à renouveler un futur séjour au sein de cet établissement !",
        "N'ayez pas peur de réserver !",
        "absolument pas à la hauteur",
        "Très déçue, pas du tout à l écoute, aucune remise en question.",
        "Toutefois, je chercherai mieux et ne reviendrai pas.",
        "on y retourne régulierement!",
        "Nous y retournerons !",
        "à refaire!",
        "Continuez ainsi.",
        "Nous recommandons cet endroit.",
        "Continuez ainsi !",
        "c'est a refaire.",
        "Bravo continuez.",
        "Bref je le recommande a",
        "Nous aurons un grand plaisir à revenir lors d'un prochain séjour",
        "j'y retournerais.",
        "Retournerons bien volontiers lors d’un prochain séjour",
        "Je suis énormément déçu qu'on ait douté de mon honnêteté ",
        "C’est un hôtel que nous recommandons.",
        "- De ne pas rester plus longtemps.",
        "Y retournerions sans hésiter!",
        "Je recommande cette appart hôtel pour tous les gens de passage à Valenciennes ou pour un plus long séjour.",
        "si l occase se représente je reviendrais",
        "Je recommande vivement et chaudement cet établissement.",
        "Nous recommandons cet hotel sans hésiter.",
        "alors n’attendez plus",
        "pour que nous revenions au printemps prochain !",
        "Nous y reviendrons avec grand plaisir.",
        "Nous vous conseillons vivement se petit bijoux.",
        "A recommander sans hésitation!",
        "nous reviendrons ",
        "Nous attendons avec impatience notre prochain séjour !",
        "Je le recommande vivement.",
        ", nous reviendrons avec plaisir",
        "Nous recommandons vivement cet endroit pour passer un très bon séjour à deux.",
        "Nous ne pourrons que recommander votre értablissement.",
        "Nous recommandons vivement cette adresse et souhaitons une belle réussite aux propriétaires.",
        "A recommander fortement!",
        "nous reviendrons .",
        "c'est inadmissible !",
        "Déçu en fait.",
        "Je recommande vivement l'hôtel des Esclargies pour tout séjour dans la région.",
        "Ns y reviendrons",
        "Bref, inacceptable!",
        "C’est une belle bulle de sérénité que nous recommandons sans modération.",
        "Je recommande ce lieu à tous voyageurs.",
        "Nous recommencerons en espérant que les chambres seront améliorées.",
        "Nous recommandons",
        "N hésitez surtout pas.",
        "Allez-y sans hésitations, vous ne le regretterez pas!",
        "Très déçu",
        "Si nous devons retourner sur Orléans ces sûr que nous y retournerons !",
        "Nous y reviendrons !",
        "S vous passez ou devez séjourner dans ce secteur touristique je recommande fortement cet établissement.",
        "Les 5 nous nous étions d'accord pour dire que la prochaine fois nous irons ailleurs:(",
        "Grosse déception dès l'arrivée, cadre loin des attentes.",
        "Nous y retournerons sans aucun problème !",
        "On faisait étape en famille, on ne s'y arrêtera plus.",
        "intolérable !",
        "Je reviendrai avec plaisir.",
        ", allez y.",
        "J'y retournerai avec plaisir lors de mes prochains passages dans le coin et le conseillerai bien volontiers.",
        "très recommandable.",
        "J y retournerai avec plaisir",
        ".c'est dommage",
        "Nous reviendrons sans hésiter pour notre prochaine escale en Corrèze!",
        "continuer ainsi nous reviendrons avec grand plaisir D-D",
        "Nous serions vraiment apprécié cet hôtel.",
        "Je le recommanderai à mon entourage.",
        "c'est décevant.",
        "Je recommande et je reviens .",
        "Nous espérons revenir.",
        "Nous y retournerons à l'occasion",
        "C'est notre seul regret",
        "Le mans est triste pour une étape",
        "vraiment j y retournerai.",
        "Je conseil vivement cet Hôtel!",
        "Nous avons beaucoup apprécier et nous le recommandons",
        ", j'y retournerai sans problème.",
        "Nous recommandons ce camping sans aucun soucis ",
        "Nous reviendrons c'est certain .",
        "je recommande vivement cet établissement.",
        "Une prochaine fois",
        "Je recommande tout à fait.",
        ",nous reviendrons.",
        "Nous ne pouvons que recommander cet hôtel proche de beaux sites",
        "nous y retournerons avec enthousiasme,",
        "si c'était à refaire, ce serait sans soucis!",
        "A faire absolument si vous êtes dans le coin!",
        "Mais soyons honnête",
        "vous pouvez y aller",
        "Je reviendrai dans cet établissement.",
        "En général, une belle découverte que je recommande.",
        "Nous recommandons cet hôtel idéalement situé.",
        "nous espérons revenir bientôt !",
        "En résumé nous recommandons sans limite.",
        "Pas déçue",
        "C'est très désagréable.",
        "Rarement déçus.",
        "J'espère vraiment y retourner dans un proche avenir!",
        "On y retournera avec plaisir sur le chemin du retour!",
        "Nous y reviendrons avec grand plaisir"
    ]
)
# Settings of the solution
settings = dict(
    bert_model='paraphrase-xlm-r-multilingual-v1',  # 'paraphrase-multilingual-MiniLM-L12-v2',
    sample_embedds_path="./sample_embedds/",
    trained_xgb_model_path="./trained_model/",
    xgb_model_name="xgb_model.bin",
    threshold=0.50
)
